# Generated by Django 4.0.5 on 2022-06-30 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=b'I00\n', db_index=True, max_length=50, verbose_name='Username')),
                ('password', models.CharField(db_index=True, max_length=50, verbose_name='Password')),
                ('email', models.EmailField(blank=b'I00\n', db_index=True, max_length=50, verbose_name='Email')),
                ('token', models.CharField(blank=True, max_length=500, null=True, verbose_name='Token')),
                ('token_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Token Expiration Datetime')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Datetime')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Datetime')),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
